---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/agentgateway.dev/agentgatewaypolicy_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: &name llm-api-auth
spec:
  targetRefs:
    # fake authentication for OpenAI-compatible clients
    # only add llm backend below
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: llm-backend-complex
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: llm-backend-fast
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: llm-backend-vision
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: llm-backend-anthropic
  traffic:
    apiKeyAuthentication:
      mode: Strict
      secretRef: *name
