---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-rgw-user
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        LANGFUSE_ACCESS_KEY: "{{ .langfuse_access_key }}"
        LANGFUSE_SECRET_KEY: "{{ .langfuse_secret_key }}"
  dataFrom:
    - extract:
        key: minio
