---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cronjob-k8s-schemas
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        APP_ID: "{{ .app_id }}"
        PRIVATE_KEY: "{{ .private_key }}"
        APP_NAME: "{{ .app_name }}"
        BOT_USER_ID: "{{ .bot_user_id }}"
        INSTALLATION_ID: "{{ .installation_id }}"
  dataFrom:
    - extract:
        key: github_app
