---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: "${APP}-pguser"
spec:
  length: 32
  symbols: 0
  noUpper: false
  allowRepeat: true
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-pguser"
spec:
  refreshPolicy: OnChange
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        port: "5432"
        host: "${CNPG_NAME:=postgres}-rw.database-system.svc.cluster.local"
        ro_host: "${CNPG_NAME:=postgres}-ro.database-system.svc.cluster.local"
        username: "${APP}"
        password: "{{ .password }}"
        db: "${APP}"
        uri: "postgresql://${APP}:{{ .password }}@${CNPG_NAME:=postgres}-rw.database-system.svc.cluster.local:5432/${APP}"
        dsn: "host=${CNPG_NAME:=postgres}-rw.database-system.svc.cluster.local port=5432 user=${APP} password={{ .password }} dbname=${APP} sslmode=disable"
        INIT_POSTGRES_DBNAME: "${APP}"
        INIT_POSTGRES_HOST: "${CNPG_NAME:=postgres}-rw.database-system.svc.cluster.local"
        INIT_POSTGRES_USER: "${APP}"
        INIT_POSTGRES_PASS: "{{ .password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .admin_pass }}"
  dataFrom:
    - extract:
        key: app-user
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "${APP}-pguser"
