---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname openebs
  namespace: gitops-system
spec:
  targetNamespace: storage-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/storage-system/openebs/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-replicated
  namespace: gitops-system
spec:
  targetNamespace: storage-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: openebs
      app.kubernetes.io/component: replicated
  interval: 10m
  path: "./kubernetes/apps/storage-system/openebs/replicated"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: false
  dependsOn:
    - name: openebs
