---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      calibre-web:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542 # gladius:external-services

        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/calibre-web
              tag: 0.6.24@sha256:01c5eee25c8883a950ba0f0f158188c2da2d6e6f122f9269648538dfa0ea97b2
            env:
              CACHE_DIR: /cache
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 470M
              limits:
                memory: 470M

    service:
      app:
        controller: calibre-web
        ports:
          http:
            port: 8083

    ingress:
      app:
        className: internal-nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.noirprime.com
        hosts:
          - host: calibre-web.noirprime.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: calibre-web-config
        advancedMounts:
          calibre-web:
            app:
              - path: /config

      media:
        type: nfs
        server: nas.noirprime.com
        path: /mnt/pool_hdd/media
        advancedMounts:
          calibre-web:
            app:
              - path: /data/nas-media
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
