---
# easytier conflict with pangolin/gerbil

name: gatus

networks:
  easytier_isolated:
    driver: bridge
    internal: false

services:
  easytier:
    image: easytier/easytier:v2.5.0
    container_name: easytier
    restart: unless-stopped
    command: -c /etc/easytier/config.toml --multi-thread
    environment:
      - EASYTIER_NETWORK=${EASYTIER_NETWORK}
      - EASYTIER_SECRET=${EASYTIER_SECRET}
    volumes:
      - /opt/docker/easytier:/etc/easytier
    ports:
      - "11010:11010/tcp"
      - "11010:11010/udp"
    configs:
      - source: easytier_config
        target: /etc/easytier/config.toml
    networks:
      - easytier_isolated
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun

  gatus:
    image: twinproduction/gatus:v5.35.0
    container_name: gatus
    restart: unless-stopped
    environment:
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY}
    volumes:
      - /opt/docker/gatus:/config
    configs:
      - source: gatus_config
        target: /config/config.yml
    network_mode: "service:easytier"
    cap_add:
      - NET_RAW # icmp
    depends_on:
      - easytier

configs:
  easytier_config:
    content: |-
      instance_name = "default"
      hostname = "vps-bifrost"
      dhcp = true
      listeners = [
          "tcp://0.0.0.0:11010",
          "udp://0.0.0.0:11010",
      ]
      rpc_portal = "0.0.0.0:0"
      [network_identity]
      network_name = "${EASYTIER_NETWORK}"
      network_secret = "${EASYTIER_SECRET}"
      [[peer]]
      uri = "tcp://opn.noirprime.com:11010"
      [flags]
      dev_name = "EasyTier"
      enable_kcp_proxy = true
      latency_first = true
      private_mode = true

  gatus_config:
    content: |-
      web:
        port: 8080
      storage:
        type: memory
      alerting:
        pushover:
          application-token: "${PUSHOVER_TOKEN}"
          user-key: "${PUSHOVER_USER_KEY}"
          title: "Router Offline"
          priority: 1
          default-alert:
            failure-threshold: 3
            success-threshold: 2
            send-on-resolved: true
      endpoints:
        - name: "OpenWrt Easytier"
          url: "icmp://10.126.126.100"
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: pushover
              failure-threshold: 10
              description: "OpenWrt unreachable."
