---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name opentelemetry-collector
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: opentelemetry-collector

  values:
    fullnameOverride: *name
    mode: deployment
    replicaCount: 1
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
    command:
      name: "otelcol-k8s"
    resources:
      requests: { cpu: 10m, memory: 128Mi }
      limits: { memory: 256Mi }
    serviceMonitor:
      enabled: true
    service:
      enabled: true
      type: ClusterIP
      trafficDistribution: PreferSameZone
    presets:
      kubernetesAttributes:
        enabled: true
    ports:
      otlp:
        enabled: true
        containerPort: 4317
        servicePort: 4317
        hostPort: null
        protocol: TCP
        appProtocol: grpc
      otlp-http:
        enabled: true
        containerPort: 4318
        servicePort: 4318
        hostPort: null
        protocol: TCP
      jaeger-compact: { enabled: false }
      jaeger-thrift: { enabled: false }
      jaeger-grpc: { enabled: false }
      zipkin: { enabled: false }
      metrics:
        enabled: true
        containerPort: 8888
        servicePort: 8888
        protocol: TCP
    alternateConfig:
      extensions:
        health_check:
          endpoint: ${env:MY_POD_IP}:13133
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: ${env:MY_POD_IP}:4317
            http:
              endpoint: ${env:MY_POD_IP}:4318
      processors:
        memory_limiter:
          check_interval: 1s
          limit_percentage: 80
          spike_limit_percentage: 25
        batch:
          send_batch_size: 1024
          send_batch_max_size: 2048
          timeout: 5s
        probabilistic_sampler:
          sampling_percentage: 10
      exporters:
        otlphttp:
          endpoint: "http://victoria-traces.monitoring-system.svc.cluster.local:10428/insert/opentelemetry/v1/traces"
      service:
        extensions: [health_check]
        telemetry:
          metrics:
            readers:
              - pull:
                  exporter:
                    prometheus:
                      host: ${env:MY_POD_IP}
                      port: 8888
          logs:
            level: info
            encoding: json
        pipelines:
          traces:
            receivers: [otlp]
            processors:
              - memory_limiter
              - k8sattributes
              - probabilistic_sampler
              - batch
            exporters: [otlphttp]
