---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.31.1
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
