---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/bootstrap/**/*"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"
          - "mkdocs.yml"
          - "pyproject.toml"
          - "uv.lock"
area/github:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
area/forgejo:
  - changed-files:
      - any-glob-to-any-file:
          - ".forgejo/**/*"
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - "kubernetes/apps/**/*"
          - "kubernetes/components/**/*"
          - "kubernetes/flux/**/*"
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - ".renovate/**/*"
          - "renovate.json5"
area/infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - "infrastructure/**/*"
area/justfile:
  - changed-files:
      - any-glob-to-any-file:
          - ".justfiles/**/*"
          - "justfile"
