---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: barman-cloud
        serverName: postgres-v1 # changeme if restored
  storage:
    size: 50Gi
    storageClass: ceph-block
  superuserSecret:
    name: cloudnative-pg
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - vchord
      - vchord_bm25
    parameters:
      effective_io_concurrency: "200"
      max_connections: "400"
      shared_buffers: "2GB"
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 6Gi

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: false
      - name: hindsight
        ensure: present
        login: true
        superuser: false

  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        # https://docs.immich.app/administration/postgres-standalone/#without-superuser-permission
        - CREATE DATABASE immich;
        - |
          \c immich
          ALTER DATABASE immich OWNER TO immich;
          CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
          CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - CREATE DATABASE hindsight;
        - |
          \c hindsight
          ALTER DATABASE hindsight OWNER TO hindsight;
          CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
          CREATE EXTENSION IF NOT EXISTS pg_tokenizer CASCADE;
          CREATE EXTENSION IF NOT EXISTS vchord_bm25 CASCADE;
          SELECT create_tokenizer('llmlingua2', $$ model = "llmlingua2" $$);

  # :: Notice: backup.barmanObjectStore is deprecated
  # :: recover cluster, uncomment below
  # bootstrap:
  #   recovery:
  #     source: postgres-v1
  # externalClusters:
  #   - name: postgres-v1
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: barman-cloud
  #         serverName: postgres-v1
