---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
entries:
  - model: authentik_flows.flow
    identifiers:
      slug: authentication
    attrs:
      name: "Default Authentication Flow"
      designation: authentication
      title: "Welcome to Noirprime"
