---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
entries:
  - model: authentik_outposts.outpost
    identifiers:
      name: authentik-embedded-outpost
    attrs:
      name: authentik-embedded-outpost
      type: proxy
      config:
        authentik_host: "https://auth.noirprime.com"
        authentik_host_insecure: false
        cookie_domain: "noirprime.com"
      providers:
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, audiomuse-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, bambuddy-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, convertx-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, frigate-go2rtc-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, frigate-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, hass-code-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, homepage-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, hubble-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, lyrion-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, metube-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, qbittorrent-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, scrypted-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, sillytavern-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, victoria-metrics-alert-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, victoria-metrics-cluster-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, victoria-metrics-logs-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, z2m-code-proxy-provider],
          ]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, z2m-proxy-provider],
          ]
