---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
entries:
  - model: authentik_policies_expression.expressionpolicy
    identifiers:
      name: policy-mfa-required
    attrs:
      expression: |
        from authentik.stages.authenticator_totp.models import TOTPDevice
        return TOTPDevice.objects.filter(
            user=request.user, confirmed=True
        ).exists()
