---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
entries:
  - model: authentik_policies_reputation.reputationpolicy
    identifiers:
      name: policy-reputation-block
    attrs:
      check_ip: true
      check_username: true
      threshold: -5
