---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
entries:
  - model: authentik_stages_password.passwordstage
    identifiers:
      name: default-authentication-password
    attrs:
      backends:
        - authentik.core.auth.InbuiltBackend
