---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: clickhouse
      sourceRef:
        kind: HelmRepository
        name: clickhouse
        namespace: flux-system
      version: 6.3.1

  values:
    global:
      defaultStorageClass: openebs-hostpath

    auth:
      username: clickhouse
      password: clickhouse_password

    shards: 1
    replicaCount: 3

    keeper:
      enabled: true

    zookeeper:
      enabled: false