---
keys:
  - &user_soulwhisper
  - &user_flux

creation_rules:
  - path_regex: kubernetes/.*/talos/.*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_soulwhisper
          - *user_flux

  - path_regex: kubernetes/.*\.sops\.ya?ml$
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - *user_soulwhisper
          - *user_flux

  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_soulwhisper
