[env]
# Kubernetes
KUBECONFIG = '{{config_root}}/kubernetes/kubeconfig'
TALOSCONFIG = '{{config_root}}/kubernetes/talos/clusterconfig/talosconfig'
# Taskfile
TASK_X_ENV_PRECEDENCE = 1
TASK_X_MAP_VARIABLES = 0