---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./validatingpolicy-audit-image-registries.yaml
  - ./validatingpolicy-audit-nonflux-writes.yaml
  - ./validatingpolicy-audit-pod-deletes.yaml
  - ./validatingpolicy-audit-pod-security-baseline.yaml
  - ./validatingpolicy-audit-rbac-escalation.yaml
  - ./validatingpolicy-protect-critical-namespaces.yaml
