---
http:
  middlewares:
    internal-only:
      ipWhiteList:
        sourceRange:
          - 10.0.0.0/8 # internal
          - 192.168.0.0/16 # internal
          - 172.16.0.0/12 # internal
          - 100.89.137.0/20 # Pangolin WireGuard
          - 100.64.0.0/10 # Headscale/Tailscale CGNAT

    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    security-headers:
      headers:
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        customResponseHeaders:
          Server: ""
          X-Forwarded-Proto: https
          X-Powered-By: ""
        forceSTSHeader: true
        hostsProxyHeaders:
          - X-Forwarded-Host
        referrerPolicy: strict-origin-when-cross-origin
        sslProxyHeaders:
          X-Forwarded-Proto: https
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
