---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        UP_UNIFI_DEFAULT_USER: "{{ .unifi_username }}"
        UP_UNIFI_DEFAULT_PASS: "{{ .unifi_password }}"
  dataFrom:
    - extract:
        key: homepage
