---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # rag embedding
        EMBEDDINGS_PROVIDER: "openai"
        EMBEDDINGS_MODEL: "BAAI/bge-m3"
        EMBEDDINGS_CHUNK_SIZE: "100"
        RAG_OPENAI_BASEURL: "https://api.siliconflow.cn/v1"
        RAG_OPENAI_API_KEY: "{{ .siliconflow }}"
  dataFrom:
    - extract:
        key: llm-api
