---
# schematic for production environment
# 88a80a46089706032472a6cb4ecbe8e19a6774d3520869dec3a203631eadbc21
customization:
  bootloader: sd-boot
  extraKernelArgs:
    # stability
    - pcie_aspm=off
    - nvme_core.default_ps_max_latency_us=0
    # hardware
    - i915.enable_guc=3
    - module_blacklist=igc
  systemExtensions:
    officialExtensions:
      - siderolabs/i915
      - siderolabs/intel-ucode
      - siderolabs/mei
      - siderolabs/nut-client
      - siderolabs/gvisor
      - siderolabs/kata-containers
