---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
endpoints:
  - url: http://nas.homelab.internal:9002/docker.io
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: gcr.io
endpoints:
  - url: http://nas.homelab.internal:9002/gcr.io
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: ghcr.io
endpoints:
  - url: http://nas.homelab.internal:9002/ghcr.io
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: registry.k8s.io
endpoints:
  - url: http://nas.homelab.internal:9002/registry.k8s.io
    overridePath: true
skipFallback: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: quay.io
endpoints:
  - url: http://nas.homelab.internal:9002/quay.io
    overridePath: true
skipFallback: true
