---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${app}-${ts}"
  namespace: "${ns}"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${app}-volsync-minio"
    destinationPVC: "${claim}"
    copyMethod: Direct
    storageClassName: openebs-rep2
    previous: ${previous}
    moverSecurityContext:
      runAsUser: ${app_uid}
      runAsGroup: ${app_gid}
      fsGroup: ${app_gid}
