---
apiVersion: v1
kind: ConfigMap
metadata:
  name: moviepilot
data:
  # basic
  ENABLE_SSL: "false"
  MOVIEPILOT_AUTO_UPDATE: "false"
  # optimization
  BIG_MEMORY_MODE: "true"
  AUTO_DOWNLOAD_USER: "all"
  SEARCH_MULTIPLE_NAME: "true"
  MEDIA_RECOGNIZE_SHARE: "false"
  PLUGIN_STATISTIC_SHARE: "false"
  SUBSCRIBE_STATISTIC_SHARE: "false"
  WORKFLOW_STATISTIC_SHARE: "false"
