---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-rep2
  annotations:
    storageclass.storage.kubernetes.io/is-default-class: "true"
parameters:
  protocol: "nvmf"
  repl: "2"
  fsType: "xfs"
  thin: "true"
  allowVolumeExpansion: "true"
  stsAffinityGroup: "true"
provisioner: io.openebs.csi-mayastor
volumeBindingMode: WaitForFirstConsumer
