---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  bootstrap:
    desc: Bootstrap Flux into a Kubernetes cluster
    cmds:
      # Install Flux
      - kubectl apply --server-side --kustomize {{.K8S_CLUSTER_DIR}}/bootstrap/flux
      # Install secrets and configmaps
      - sops --decrypt {{.K8S_CLUSTER_DIR}}/bootstrap/flux/age-key.sops.yaml | kubectl apply -f -
      - sops --decrypt {{.K8S_CLUSTER_DIR}}/flux/vars/cluster-secrets.sops.yaml | kubectl apply -f -
      - kubectl apply --server-side --filename {{.K8S_CLUSTER_DIR}}/flux/vars/cluster-settings.yaml
      # Install Flux Kustomization resources
      - kubectl apply --server-side --kustomize {{.K8S_CLUSTER_DIR}}/flux/config
    requires:
      vars:
        - K8S_CLUSTER
    preconditions:
      - sh: kubectl config get-contexts {{.K8S_CLUSTER}}
        msg: "Kubectl context {{.K8S_CLUSTER}} not found"
      - test -f $HOME/.config/age/keys.txt
      - test -f {{.K8S_CLUSTER_DIR}}/bootstrap/flux/age-key.sops.yaml
      - test -f {{.K8S_CLUSTER_DIR}}/flux/vars/cluster-settings.yaml
      - test -f {{.K8S_CLUSTER_DIR}}/flux/vars/cluster-secrets.sops.yaml
      - sops --decrypt {{.K8S_CLUSTER_DIR}}/bootstrap/flux/age-key.sops.yaml
      - sops --decrypt {{.K8S_CLUSTER_DIR}}/flux/vars/cluster-secrets.sops.yaml
      - kustomize build {{.K8S_CLUSTER_DIR}}/bootstrap/flux
      - kustomize build {{.K8S_CLUSTER_DIR}}/flux/config

  apply-ks:
    desc: Apply a Flux Kustomization resource for a cluster
    summary: |
      Args:
        PATH: Path to the Flux Kustomization resource (required)
        NAME: Name of the Flux Kustomization to apply (default: last segment of <path> variable)
        NS: Namespace the Flux Kustomization exists in (default: flux-system)
    cmds:
      - flux build ks {{.KS_NAME}}
        --namespace {{.NS}}
        --kustomization-file {{.KUSTOMIZATION_FILE}}
        --path {{.KUSTOMIZATION_PATH}}
        {{ if contains "not found" .KUSTOMIZATION_FOUND }}--dry-run{{ end }}
        |
        kubectl apply --server-side --field-manager=kustomize-controller -f -
    vars:
      NS: '{{.NS | default "flux-system"}}'
      KUSTOMIZATION_PATH: "{{.K8S_CLUSTER_DIR}}/apps/{{.PATH}}"
      KUSTOMIZATION_FILE: "{{.KUSTOMIZATION_PATH}}/ks.yaml"
      KS_NAME: '{{ .name | default (base .PATH) }}'
      KUSTOMIZATION_FOUND:
        sh: flux --namespace {{.NS}} get kustomization {{.KS_NAME}} 2>&1
    requires:
      vars:
        - K8S_CLUSTER
        - PATH
    preconditions:
      - sh: "test -f {{.KUSTOMIZATION_FILE}}"
        msg: "Kustomization file {{.KUSTOMIZATION_FILE}} not found"

  delete-ks:
    desc: Delete a Flux Kustomization resource for a cluster
    summary: |
      Args:
        PATH: Path to the Flux Kustomization resource (required)
        NAME: Name of the Flux Kustomization to apply (default: last segment of <path> variable)
        NS: Namespace the Flux Kustomization exists in (default: flux-system)
    cmds:
      - flux build ks {{.KS_NAME}}
        --namespace {{.NS}}
        --kustomization-file {{.KUSTOMIZATION_FILE}}
        --path {{.KUSTOMIZATION_PATH}}
        --dry-run
        |
        kubectl delete -f -
    vars:
      NS: '{{.NS | default "flux-system"}}'
      KUSTOMIZATION_PATH: "{{.K8S_CLUSTER_DIR}}/apps/{{.PATH}}"
      KUSTOMIZATION_FILE: "{{.KUSTOMIZATION_PATH}}/ks.yaml"
      KS_NAME: '{{ .name | default (splitList "/" .PATH | last) }}'
      KUSTOMIZATION_FOUND:
        sh: flux --namespace {{.NS}} get kustomization {{.KS_NAME}} 2>&1
    requires:
      vars:
        - K8S_CLUSTER
        - PATH
    preconditions:
      - sh: "test -f {{.KUSTOMIZATION_FILE}}"
        msg: "Kustomization file {{.KUSTOMIZATION_FILE}} not found"