---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname crunchy-postgres-operator
  namespace: gitops-system
spec:
  targetNamespace: database-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/database-system/crunchy-postgres-operator/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname crunchy-postgres-operator-cluster
  namespace: gitops-system
spec:
  targetNamespace: database-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/database-system/crunchy-postgres-operator/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: true
  dependsOn:
    - name: crunchy-postgres-operator
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname crunchy-postgres-operator-secretstore
  namespace: gitops-system
spec:
  targetNamespace: database-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/database-system/crunchy-postgres-operator/clustersecretstore
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: true
  dependsOn:
    - name: crunchy-postgres-operator-cluster
    - name: external-secrets
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname crunchy-postgres-userinit-controller
  namespace: gitops-system
spec:
  targetNamespace: database-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/database-system/crunchy-postgres-operator/userinit-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: true
  dependsOn:
    - name: crunchy-postgres-operator-cluster
