---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name kagent
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kagent

  values:
    controller:
      replicas: 2
    database:
      postgres:
        url: "postgresql://kagent:kagent@postgres-rw.database-system.svc.cluster.local:5432/kagent"
        vectorEnabled: true
        bundled:
          enabled: false
    kagent-tools:
      enabled: true
      tools:
        metrics:
          servicemonitor:
            enabled: true
    # providers
    providers:
      default: ollama
    ollama:
      model: "gemma-4:e4b"
      config:
        host: "ollama.servitor-apps.svc.cluster.local:11434"
    # kmcp
    kmcp:
      enabled: false
    # agents for tests
    agents:
      argo-rollouts-agent:
        enabled: false
      istio-agent:
        enabled: false
    tools:
      grafana-mcp:
        secretRef: "grafana-mcp"
    # * todo: agentgateway support
    # proxy:
    #   url: "http://agentgateway-proxy.networking-system.svc.cluster.local"
    # * todo: rewrite agents
    # path: /mcp/prefix_tool

  # add postgres init
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: kagent-controller
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: kagent-controller
              spec:
                template:
                  spec:
                    initContainers:
                      - name: init-db
                        image: ghcr.io/home-operations/postgres-init:18
                        envFrom:
                          - secretRef:
                              name: kagent-initdb
