---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &name kagent
spec:
  jobLabel: *name
  namespaceSelector:
    matchNames:
      - servitor-apps
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  endpoints:
    - port: controller
      path: /metrics
      scheme: http
      honorLabels: true
