---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name kagent-crds
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kagent-crds
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name kmcp-crds
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kmcp-crds
