---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname intel-device-plugins-operator
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: "./kubernetes/main/apps/kube-system/intel-device-plugins/operator"
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  timeout: 5m
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager
    - name: node-feature-discovery-rules
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname intel-device-plugins-gpu
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: "./kubernetes/main/apps/kube-system/intel-device-plugins/gpu"
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
  wait: true
  dependsOn:
    - name: intel-device-plugins-operator
