---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # the 1Password item stores the credentials file base64url-encoded
        1password-credentials.json: "{{ .credentials | b64dec }}"
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: 1password-api
