---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name onepassword-connect
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: onepassword-connect

  values:
    connect:
      replicas: 1
      credentialsName: *name
      credentialsKey: 1password-credentials.json
      api:
        httpPort: 8080
        imageRepository: ghcr.io/1password/connect-api
        serviceMonitor:
          enabled: true
      sync:
        imageRepository: ghcr.io/1password/connect-sync
