---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiomuse
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        AI_MODEL_PROVIDER: "OPENAI"
        OPENAI_BASE_URL: "http://agentgateway-proxy.networking-system.svc.cluster.local:80/chat/fast"
        # OPENAI_MODEL_NAME: "deepseek-v4-flash"
        OPENAI_API_KEY: "{{ .agentgateway_auth_token }}"
  dataFrom:
    - extract:
        key: llm-api
