---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiomuse
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        AI_MODEL_PROVIDER: "OPENAI"
        OPENAI_BASE_URL: "http://agentgateway-proxy.networking-system.svc.cluster.local:80/chat"
        OPENAI_MODEL_NAME: "fast"
        OPENAI_API_KEY: "{{ .agentgateway_api_auth }}"
        # navidrome
        NAVIDROME_USER: "{{ .admin_user }}"
        NAVIDROME_PASSWORD: "{{ .admin_pass }}"
  dataFrom:
    - extract:
        key: llm-api
    - extract:
        key: app-user
