---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &name victoria-traces
spec:
  jobLabel: *name
  namespaceSelector:
    matchNames:
      - monitoring-system
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  endpoints:
    - port: http
      path: /metrics
      honorLabels: true
