---
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
hubble:
  # disable hubble, use ebpf monitoring instead
  enabled: false
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
ipam:
  mode: "kubernetes"
k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
operator:
  rollOutPods: true
  prometheus:
    enabled: true
prometheus:
  enabled: true
rollOutCiliumPods: true
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cni:
  exclusive: false
l2announcements:
  enabled: true
loadBalancer:
  acceleration: native
  mode: hybrid
bgpControlPlane:
  enabled: true
bpf:
  masquerade: true
  datapathMode: netkit
  tproxy: true
bandwidthManager:
  enabled: true
  bbr: true
devices: bond+
enableIPv4BIGTCP: true
routingMode: native
ipv4NativeRoutingCIDR: 10.100.0.0/17
autoDirectNodeRoutes: true
endpointRoutes:
  enabled: true
