---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nginx-shared
  namespace: gitops-system
spec:
  targetNamespace: networking-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/networking-system/ingress-nginx/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: true
  dependsOn:
    - name: cert-manager-issuers
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nginx-external
  namespace: gitops-system
spec:
  targetNamespace: networking-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/networking-system/ingress-nginx/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: false
  dependsOn:
    - name: nginx-shared
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nginx-internal
  namespace: gitops-system
spec:
  targetNamespace: networking-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/networking-system/ingress-nginx/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: false
  dependsOn:
    - name: nginx-shared
