---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/agentgateway.dev/agentgatewaybackend_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: &name home-assistant-mcp
spec:
  mcp:
    targets:
      - name: *name
        protocol: StreamableHTTP
        selector:
          services:
            matchLabels:
              app.kubernetes.io/name: *name
            matchNamespaces: ["smarthome-apps"]
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name home-assistant-mcp
spec:
  parentRefs:
    - name: agentgateway-proxy
      sectionName: mcp
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - name: *name
          group: agentgateway.dev
          kind: AgentgatewayBackend
