---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/agentgateway.dev/agentgatewaybackend_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: kubernetes-mcp-backend
spec:
  mcp:
    targets:
      - name: kubernetes
        selector:
          services:
            matchLabels:
              app.kubernetes.io/name: kubernetes-agent-mcp
            matchNamespaces:
              - servitor-apps
        protocol: StreamableHTTP
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubernetes-mcp-route
spec:
  parentRefs:
    - name: agentgateway-proxy
      sectionName: mcp
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - name: kubernetes-mcp-backend
          group: agentgateway.dev
          kind: AgentgatewayBackend
