---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.16.3

  valuesFrom:
    - kind: ConfigMap
      name: cilium-values

  values:
    hubble:
      serviceMonitor:
        enabled: true

      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium

      relay:
        prometheus:
          serviceMonitor:
            enabled: true

      ui:
        ingress:
          enabled: true
          className: "internal-nginx"
          annotations:
            external-dns.alpha.kubernetes.io/target: ingress-int.noirprime.com
          hosts:
            - hubble-main.noirprime.com

    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium

    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true

    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
