---
apiVersion: v1
kind: ConfigMap
metadata:
  name: langfuse-database
data:
  NEXTAUTH_URL: "https://langfuse.noirprime.com"
  TELEMETRY_ENABLED: "false"
  LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "true"
  CLICKHOUSE_MIGRATION_URL: "clickhouse://langfuse-database:9000"
  CLICKHOUSE_URL: "http://langfuse-database:8123"
  CLICKHOUSE_USER: "langfuse-database"
  CLICKHOUSE_PASSWORD: "langfuse-database"
  CLICKHOUSE_CLUSTER_ENABLED: "false"
  LANGFUSE_USE_AZURE_BLOB: "false"
  LANGFUSE_USE_OCI_NATIVE_OBJECT_STORAGE: "false"
  LANGFUSE_OCI_AUTH_TYPE: "workload_identity"
  LANGFUSE_S3_EVENT_UPLOAD_BUCKET: "langfuse"
  LANGFUSE_S3_EVENT_UPLOAD_REGION: "auto"
  LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
  LANGFUSE_S3_EVENT_UPLOAD_PREFIX: "events/"
  LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: "langfuse"
  LANGFUSE_S3_MEDIA_UPLOAD_REGION: "auto"
  LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true"
  LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: "media/"
  LANGFUSE_S3_BATCH_EXPORT_ENABLED: "false"
  LANGFUSE_S3_BATCH_EXPORT_BUCKET: "langfuse"
  LANGFUSE_S3_BATCH_EXPORT_PREFIX: "exports/"
  LANGFUSE_S3_BATCH_EXPORT_REGION: "auto"
  LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE: "true"
  REDIS_PORT: "6379"
  REDIS_TLS_ENABLED: "false"
