---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-database
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        LANGFUSE_INIT_USER_EMAIL: "{{ .admin_email }}"
        LANGFUSE_INIT_USER_NAME: "{{ .admin_user }}"
        LANGFUSE_INIT_USER_PASSWORD: "{{ .admin_pass }}"
        LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: &bucket_endpoint "http://rook-ceph-rgw-ceph-objectstore.storage-system.svc.cluster.local"
        LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: &bucket_access_key_id "{{ .langfuse_access_key }}"
        LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: &bucket_secret_access_key "{{ .langfuse_secret_key }}"
        LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: *bucket_endpoint
        LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: *bucket_access_key_id
        LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: *bucket_secret_access_key
        LANGFUSE_S3_BATCH_EXPORT_ENDPOINT: *bucket_endpoint
        LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID: *bucket_access_key_id
        LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY: *bucket_secret_access_key
        ENCRYPTION_KEY: "{{ .langfuse_encryption_key }}"
        NEXTAUTH_SECRET: "{{ .langfuse_secret }}"
        SALT: "{{ .langfuse_salt }}"
  dataFrom:
    - extract:
        key: app_user
    - extract:
        key: minio
    - extract:
        key: encryption_cipher
