---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-homelab
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: actions-runner-controller-charts/gha-runner-scale-set
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system

  values:
    runnerGroup: arc-homelab
    runnerScaleSetName: arc-homelab

    githubConfigUrl: https://github.com/soulwhisper

    minRunners: 0
    maxRunners: 6

    containerMode:
      type: "dind"

    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: dev

    listenerTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: arc-homelab-listener
      spec:
        containers: []

    template:
      metadata:
        labels:
          app.kubernetes.io/name: arc-homelab-runner
      spec:
        containers:
          - name: runner
            image: ghcr.io/onedr0p/actions-runner:2.321.0@sha256:4bca15db7257dd98df5fd379a51e4edd80c7629b04306330aada63d6ad17a3a9
            command: ["/home/runner/run.sh"]

  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_id
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_installation_id
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_private_key
      targetPath: githubConfigSecret.github_app_private_key