---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/kagent.dev/mcpserver_v1alpha1.json
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: kubernetes
  labels:
    kagent.dev/discovery: disabled
spec:
  deployment:
    args:
      - "kubernetes-mcp-server@latest"
      - "--kubeconfig"
      - "/root/.kube/config"
      - "--config"
      - "/root/config.yaml"
    cmd: uvx
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    volumeMounts:
      - name: kubernetes-secret
        mountPath: /root/.kube
        readOnly: true
      - name: kubernetes-config
        mountPath: /root
        readOnly: true
    volumes:
      - name: kubernetes-secret
        secret:
          secretName: kubernetes-agent
          items:
            - key: config
              path: config
      - name: kubernetes-config
        configMap:
          name: kubernetes-agent
          items:
            - key: config.toml
              path: config.toml
  transportType: http
  HTTPTransport:
    targetPort: 8080
    path: "/mcp"
