---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./context/ks.yaml
  - ./firecrawl/ks.yaml
  - ./fluxcd/ks.yaml
  - ./forgejo/ks.yaml
  - ./github/ks.yaml
  - ./grafana/ks.yaml
  - ./hindsight-aiops/ks.yaml
  - ./hindsight-homelab/ks.yaml
  - ./home-assistant/ks.yaml
  - ./kubernetes/ks.yaml
  - ./trendradar/ks.yaml
  - ./victoria-logs/ks.yaml
  - ./victoria-metrics/ks.yaml
