---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # These mcp servers dependsOn toolhive and original apps
  # servers
  - ./context/ks.yaml
  - ./fast-note-sync/ks.yaml
  - ./firecrawl/ks.yaml
  - ./fluxcd/ks.yaml
  - ./github/ks.yaml
  - ./grafana/ks.yaml
  - ./home-assistant/ks.yaml
  - ./kubernetes/ks.yaml
  - ./victoria-logs/ks.yaml
