---
ingress:
  - hostname: "noirprime.com"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.noirprime.com
  - hostname: "*.noirprime.com"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.noirprime.com
  - service: http_status:404
