---
http:
  routers:
    pangolin-redirect:
      rule: "Host(`pangolin.noirprime.com`)"
      service: pangolin-next
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    pangolin-next:
      rule: "Host(`pangolin.noirprime.com`) && !PathPrefix(`/api/v1`)"
      service: pangolin-next
      entryPoints:
        - websecure
      middlewares:
        - security-headers
      tls:
        certResolver: letsencrypt
        domains:
          - main: "noirprime.com"
            sans:
              - "*.noirprime.com"

    pangolin-api:
      rule: "Host(`pangolin.noirprime.com`) && PathPrefix(`/api/v1`)"
      service: pangolin-api
      entryPoints:
        - websecure
      middlewares:
        - security-headers
      tls:
        certResolver: letsencrypt

    pangolin-ws:
      rule: "Host(`pangolin.noirprime.com`)"
      service: pangolin-api
      entryPoints:
        - websecure
      middlewares:
        - security-headers
      tls:
        certResolver: letsencrypt

  services:
    pangolin-next:
      loadBalancer:
        servers:
          - url: "http://pangolin:3002"

    pangolin-api:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000"
