---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted-apps
components:
  - ../../components/namespace
resources:
  - ./bambuddy/ks.yaml
  - ./convertx/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./homepage/ks.yaml
  - ./karakeep/ks.yaml
  - ./miniflux/ks.yaml
  - ./netbox/ks.yaml
  - ./rsshub/ks.yaml
  - ./searxng/ks.yaml
  - ./stirling-pdf/ks.yaml
