---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pangolin-newt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        NEWT_ID: "{{ .newt_id }}"
        NEWT_SECRET: "{{ .newt_secret }}"
        PANGOLIN_ENDPOINT: "{{ .endpoint }}"
  dataFrom:
    - extract:
        key: pangolin
