---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        DJANGO_SECRET_KEY: "{{ .dispatcharr }}"
        DJANGO_SUPERUSER_USERNAME: "{{ .admin_user }}"
        DJANGO_SUPERUSER_EMAIL: "{{ .admin_email }}"
        DJANGO_SUPERUSER_PASSWORD: "{{ .admin_pass }}"
  dataFrom:
    - extract:
        key: encryption_cipher
    - extract:
        key: app-user
