---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: offsite
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .admin_user }}"
        AWS_SECRET_ACCESS_KEY: "{{ .admin_pass }}"
        RCLONE_CRYPT_PASSWORD: "{{ .rclone }}"
  dataFrom:
    - extract:
        key: app-user
    - extract:
        key: encryption-cipher
