---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # app
  - ./cronjob-dr-test.yaml
  - ./cronjob-offsite-sync.yaml
  # utils
  - ./externalsecret.yaml
  - ./prometheusrule.yaml
