---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng
data:
  limiter.toml: |
    [botdetection]
    ipv4_prefix = 32
    ipv6_prefix = 48
    trusted_proxies = [
      '127.0.0.0/8',
      '10.0.0.0/8'
    ]
    [botdetection.ip_limit]
    filter_link_local = true
    link_token = true
    [botdetection.ip_lists]
    block_ip = []
    pass_ip = [
      '10.0.0.0/8',
      '172.16.0.0/12',
      '192.168.0.0/16'
    ]
    pass_searxng_org = false

  settings.yml: |
    ---
    use_default_settings: true
    server:
      limiter: true
      image_proxy: true
      method: GET
      public_instance: false
    search:
      autocomplete: duckduckgo
      favicon_resolver: duckduckgo
      languages:
        - all
        - en
        - en-US
      formats:
        - html
        - json
    general:
      instance_name: Search
    ui:
      default_theme: simple
      infinite_scroll: true
      query_in_title: true
      results_on_new_tab: true
      static_use_hash: true
      theme_args:
        simple_style: auto
    categories_as_tabs:
      general:
      images:
      videos:
      map:
    plugins:
      searx.plugins.calculator.SXNGPlugin:
        active: true
      searx.plugins.hash_plugin.SXNGPlugin:
        active: true
      searx.plugins.self_info.SXNGPlugin:
        active: true
      searx.plugins.tracker_url_remover.SXNGPlugin:
        active: true
      searx.plugins.unit_converter.SXNGPlugin:
        active: true
      searx.plugins.ahmia_filter.SXNGPlugin:
        active: true
      searx.plugins.hostnames.SXNGPlugin:
        active: true
      searx.plugins.oa_doi_rewrite.SXNGPlugin:
        active: true
      searx.plugins.tor_check.SXNGPlugin:
        active: false
    hostnames:
      high_priority:
        - (.*\.)?wikipedia.org$
        - (.*\.)?github.com$
        - (.*\.)?reddit.com$
        - (.*\.)?docker.com$
        - (.*\.)?archlinux.org$
        - (.*\.)?stackoverflow.com$
        - (.*\.)?askubuntu.com$
        - (.*\.)?superuser.com$
        - (.*)\/blog\/(.*)
