---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/agentgateway.dev/agentgatewaypolicy_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: agentgateway-policies
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: agentgateway-proxy
  frontend:
    tracing:
      backendRef:
        name: opentelemetry-collector
        namespace: monitoring-system
        port: 4317
      protocol: GRPC
      clientSampling: "true"
      randomSampling: "true"
      attributes:
        add:
          - expression: 'request.headers["x-header-tag"]' # yamllint disable-line rule:quoted-strings
            name: request
          - expression: "request.host"
            name: host
  traffic:
    phase: PreRouting
    transformation:
      request:
        set:
          # add headers
          - name: "x-model"
            value: "json(request.body).model"
          - name: "x-priority"
            value: 'coalesce(json(request.body).priority, "standard")'
