---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
data:
  openid.yaml: |
    configure_url: "https://auth.noirprime.com/application/o/hass/.well-known/openid-configuration"
    client_id: !env_var OIDC_CLIENT_ID
    client_secret: !env_var OIDC_CLIENT_SECRET
    scope: "openid profile email"
    username_field: "email"
    block_login: false
