---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
data:
  recorder.yaml: |
    db_url: !env_var RECORDER_DB_URL
    purge_keep_days: 365
    commit_interval: 5
    exclude:
      domains:
        - updater
        - media_player
      entity_globs:
        - sensor.*_signal_strength
        - sensor.*_rssi
        - sensor.last_boot
        - sensor.date
        - sun.sun
      event_types:
        - call_service
