---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # hass-sgcc
        sgcc_username: "{{ .sgcc_username }}"
        sgcc_password: "{{ .sgcc_password }}"
        ark_api_key: "{{ .volcengine }}"
        # oidc
        oidc_client_id: "{{ .hass_oidc_client_id }}"
        oidc_client_secret: "{{ .hass_oidc_client_secret }}"
  dataFrom:
    - extract:
        key: home-assistant
    - extract:
        key: llm-api
    - extract:
        key: authentik
