---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: ceph-node-diskspace-warning-local
  namespace: monitoring-system
spec:
  matchers:
    - name: alertname
      value: CephNodeDiskspaceWarning
    - name: device
      value: /dev/sd.*
      matchType: "=~"
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: ceph-node-diskspace-warning-nfs
  namespace: monitoring-system
spec:
  matchers:
    - name: alertname
      value: CephNodeDiskspaceWarning
    - name: mountpoint
      value: /etc/nfsmount.conf
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: nas-memory-usage
  namespace: monitoring-system
spec:
  matchers:
    - name: alertname
      value: NodeMemoryHighUtilization
    - name: instance
      value: nas.homelab.internal:9100
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: talos-kubelet-ephemeral-fs
  namespace: monitoring-system
spec:
  matchers:
    - name: alertname
      value: NodeFilesystemAlmostOutOfSpace
    - name: mountpoint
      value: /var/lib/kubelet/pods
      matchType: "=~"
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: bond-flap-during-upgrade
  namespace: monitoring-system
spec:
  matchers:
    - name: alertname
      value: NodeNetworkInterfaceFlapping
    - name: device
      value: ^(bond0|enp2s0f.+)$
      matchType: "=~"
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: cilium-rolling-upgrade-churn
  namespace: monitoring-system
spec:
  matchers:
    - name: alertname
      value: CiliumIdentitiesChurning
