---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname openebs
  namespace: flux-system
spec:
  targetNamespace: openebs
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/main/apps/openebs/openebs/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-replicated
  namespace: flux-system
spec:
  targetNamespace: openebs
  commonMetadata:
    labels:
      app.kubernetes.io/name: openebs
      app.kubernetes.io/component: replicated
  interval: 30m
  timeout: 5m
  path: "./kubernetes/main/apps/openebs/openebs/replicated"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  dependsOn:
    - name: openebs
