---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: clickhouse
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/clickhouse