---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coroot
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  url: https://coroot.github.io/helm-charts