---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        OAUTH_CLIENT_ID: "{{ .immich_oidc_client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .immich_oidc_client_secret }}"
  dataFrom:
    - extract:
        key: authentik
