---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # shared
  - ./embeddingserver.yaml
  - ./mcptelemetryconfig.yaml
  # groups
  # httproute is removed to reduce authentication and authorization complexity
  - ./mcpgroup.yaml
  - ./scrapeconfig.yaml
  - ./virtualmcpserver.yaml
