---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name vmcp-internal-ro
spec:
  staticConfigs:
    - targets: ["vmcp-internal-ro.servitor-apps.svc.cluster.local:4483"]
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name vmcp-internal-rw
spec:
  staticConfigs:
    - targets: ["vmcp-internal-rw.servitor-apps.svc.cluster.local:4483"]
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name vmcp-external
spec:
  staticConfigs:
    - targets: ["vmcp-external.servitor-apps.svc.cluster.local:4483"]
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
