---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name kubernetes-mcp
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kubernetes-mcp

  values:
    fullnameOverride: *name
    config:
      port: "8080"
      log_level: 2
      read_only: true
      stateless: true
      list_output: "yaml"
      toolsets:
        - core
        - config
        - helm
        - kubevirt
      denied_resources:
        - group: ""
          version: v1
          kind: Secret
        - group: external-secrets.io
          version: v1
          kind: ExternalSecret
    metrics:
      serviceMonitor:
        enabled: true
    ingress:
      enabled: false
