---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentgateway-api-keys
  labels:
    ai.home-ops.io/group: agents
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        api-key: "{{ .custom_agent }}"
  dataFrom:
    - extract:
        key: llm-api
