---
name: derper

services:
  derper:
    image: "ghcr.io/ngc7331/docker-derper:1.94.2"
    container_name: "derper"
    restart: "unless-stopped"
    ports:
      - "48484:443/tcp"
      - "48484:3478/udp"
    environment:
      - "PGID=101"
      - "DERP_ENABLE_HTTP=false"
      - "DERP_VERIFY_CLIENTS=true"
      - "DERP_HOSTNAME=derp.noirprime.com"
      - "DERP_CERTMODE=acme.sh"
      - "ACME_SH_EMAIL=admin@noirprime.com"
    env_file:
      - derper.sops.env
    volumes:
      - "/var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock"
      - "/volume3/docker/derper:/data"
