---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: trpg
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
