---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
entries:
  - model: authentik_providers_proxy.proxyprovider
    id: z2m-proxy-provider
    identifiers:
      name: &provider z2m-proxy-provider
    attrs:
      name: *provider
      authorization_flow:
        !Find [
          authentik_flows.flow,
          [slug, default-provider-authorization-implicit-consent],
        ]
      invalidation_flow:
        !Find [
          authentik_flows.flow,
          [slug, default-invalidation-flow],
        ]
      mode: forward_domain
      external_host: &domain "https://z2m.noirprime.com"
      access_token_validity: "hours=12"
      cookie_domain: "noirprime.com"
  - model: authentik_core.application
    id: z2m
    identifiers:
      slug: &name z2m
    attrs:
      name: *name
      provider: !KeyOf z2m-proxy-provider
      meta_launch_url: *domain
      group: "SmartHome"
      policy_engine_mode: all
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf z2m
      group: !Find [authentik_core.group, [name, homelab-admin]]
      order: 0
    attrs: { enabled: true, timeout: 30 }
