---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./coroot/ks.yaml
  - ./grafana/ks.yaml
  - ./grafana-alloy/ks.yaml
  - ./qryn/ks.yaml
  - ./kromgo/ks.yaml

