---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
entries:
  - model: authentik_providers_saml.samlpropertymapping
    id: &mapping rook-ceph-dashboard-username
    identifiers:
      name: "SAML Mapping: Username"
    attrs:
      name: "SAML Mapping: Username"
      saml_name: "username"
      expression: |
        return request.user.username
  - model: authentik_providers_saml.samlprovider
    id: &provider rook-ceph-dashboard-saml-provider
    identifiers:
      name: *provider
    attrs:
      name: *provider
      authorization_flow:
        !Find [
          authentik_flows.flow,
          [slug, default-provider-authorization-implicit-consent],
        ]
      acs_url: "https://rook.noirprime.com/auth/saml2"
      sp_binding: post
      audience: "https://rook.noirprime.com/auth/saml2/metadata"
      issuer: "https://auth.noirprime.com/"
      name_id_mapping: !KeyOf *mapping
      signing_kp:
        !Find [
          authentik_crypto.certificatekeypair,
          [name, "authentik Self-signed Certificate"],
        ]
      property_mappings:
        - !KeyOf *mapping
        - !Find [
            authentik_providers_saml.samlpropertymapping,
            [managed, "goauthentik.io/providers/saml/name"],
          ]
        - !Find [
            authentik_providers_saml.samlpropertymapping,
            [managed, "goauthentik.io/providers/saml/email"],
          ]
  - model: authentik_core.application
    id: &name rook-ceph-dashboard
    identifiers:
      slug: *name
    attrs:
      name: *name
      provider: !KeyOf *provider
      meta_launch_url: "https://rook.noirprime.com"
      group: "Storage"
      policy_engine_mode: all
  - model: authentik_policies_binding.policybinding
    identifiers:
      target: !KeyOf *name
      group: !Find [authentik_core.group, [name, homelab-admin]]
      order: 0
    attrs: { enabled: true, timeout: 30 }
