---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mcp
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes
  data:
    - secretKey: GRAFANA_SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: grafana-mcp-sa
        property: token
