---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/kagent.dev/mcpserver_v1alpha1.json
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: grafana
  labels:
    kagent.dev/discovery: disabled
spec:
  deployment:
    args:
      - "mcp-grafana@latest"
      - "-t"
      - "streamable-http"
      - "--address"
      - "0.0.0.0:8000"
    cmd: uvx
    env:
      GRAFANA_URL: "http://grafana-service.monitoring-system.svc.cluster.local:3000"
    secretRefs:
      - grafana-mcp
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  transportType: http
  HTTPTransport:
    targetPort: 8000
    path: "/mcp"
