---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name home-assistant
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: smarthome-apps
  path: "./kubernetes/apps/smarthome-apps/home-assistant/app"
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_STORAGECLASS: ceph-filesystem
      VOLSYNC_SNAPSHOTCLASS: ceph-filesystem-snapshot
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name home-assistant-sgcc
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: smarthome-apps
  path: "./kubernetes/apps/smarthome-apps/home-assistant/sgcc"
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name home-assistant-mcp
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: monitoring-system
  path: "./kubernetes/apps/monitoring-system/home-assistant/mcp"
  dependsOn:
    - name: home-assistant
      namespace: smarthome-apps
    - name: kagent
      namespace: servitor-apps
