---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/kagent.dev/mcpserver_v1alpha1.json
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: victoria-logs
  labels:
    kagent.dev/discovery: disabled
spec:
  deployment:
    image: "ghcr.io/victoriametrics-community/mcp-victorialogs:7.1.0"
    env:
      VL_INSTANCE_ENTRYPOINT: "http://victoria-logs-server.monitoring-system.svc.cluster.local:9428"
      MCP_SERVER_MODE: "http"
      MCP_LISTEN_ADDR: ":8081"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  transportType: http
  HTTPTransport:
    targetPort: 8081
    path: "/mcp"
