---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: ${APP}-dragonfly
spec:
  length: 32
  symbols: 0
  noUpper: false
  allowRepeat: true
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-dragonfly
spec:
  # CreatedOnce: cache password only needs to be stable, rotate by deleting
  # the target Secret
  refreshPolicy: CreatedOnce
  target:
    name: ${APP}-dragonfly-secret
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: ${APP}-dragonfly
