---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitor-apps
components:
  - ../../components/namespace
resources:
  # mcp
  - ./mcp
  # app
  - ./dify/ks.yaml
  - ./firecrawl/ks.yaml
  - ./hermes-agent/ks.yaml
  - ./hindsight/ks.yaml
  - ./honcho/ks.yaml
  - ./langfuse/ks.yaml
  - ./open-notebook/ks.yaml
  - ./sillytavern/ks.yaml
  - ./tei/ks.yaml
