---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitor-apps
components:
  - ../../components/namespace
resources:
  # app
  - ./astrbot/ks.yaml
  - ./dify/ks.yaml
  - ./langfuse/ks.yaml
  - ./sillytavern/ks.yaml
  - ./tei/ks.yaml
  # mcp
  - ./mcp
