---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # app
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  # utils
  - ./service.yaml
  - ./httproute.yaml
  # patches
  # * saml2 support
  # - ./patches/backendconfigpolicy.yaml
  # * official chart sc might be missing
  # - ./patches/storageclass.yaml
