---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/gateway.kgateway.dev/gatewayparameters_v1alpha1.json
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: kgateway-params
spec:
  kube:
    deployment:
      replicas: 3 # bgp advertise 3 nodes
    podTemplate:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          matchLabelKeys:
            - gateway.networking.k8s.io/gateway-name
            - pod-template-hash
    envoyContainer:
      bootstrap:
        logFormat:
          json:
            time: "%Y-%m-%dT%T.%eZ"
            level: "%l"
            logger: "%n"
            thread: "%t"
            source: "%g:%#"
            message: "%v"
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          memory: "1Gi"
    service:
      externalTrafficPolicy: Local
    podDisruptionBudget:
      spec:
        minAvailable: 1
        unhealthyPodEvictionPolicy: AlwaysAllow
