---
# yaml-language-server: $schema=https://soulwhisper.github.io/CRD-catalog/gateway.kgateway.dev/gatewayparameters_v1alpha1.json
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: kgateway-params
spec:
  kube:
    deployment:
      replicas: 2
    podTemplate:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          matchLabelKeys:
            - gateway.networking.k8s.io/gateway-name
            - pod-template-hash
    envoyContainer:
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          memory: "1Gi"
    service:
      externalTrafficPolicy: Local
    podDisruptionBudget:
      spec:
        minAvailable: 1
