---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kopiur.home-operations.com/repositoryreplication_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: RepositoryReplication
metadata:
  name: nas-to-offsite
spec:
  sourceRef:
    kind: ClusterRepository
    name: nas
  destination:
    s3:
      bucket: kopiur
      endpoint: "172.19.82.10:9000"
      tls:
        disableTls: true
      auth:
        secretRef:
          name: kopiur-repository-secret
          namespace: storage-system
  schedule:
    cron: "30 5 * * *" # after CNPG backups (03:00) and kopia full maintenance (03:00)
    jitter: 30m
    timezone: Asia/Shanghai
