---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: volsync
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system

  values:
    manageCRDs: true
    metrics:
      disableAuth: true
