---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints-apps-static
data:
  app-homepage.yaml: |
    version: 1
    entries:
      - model: authentik_core.application
        identifiers:
          slug: homepage
        attrs:
          name: homepage
          meta_launch_url: "https://home.noirprime.com"
