---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k8s-rules
spec:
  groups:
    - name: k8s.rules
      rules:
        - alert: HighContainerNonZeroExits
          annotations:
            summary: "{{ $labels.namespace }}/{{ $labels.pod }} container {{ $labels.container }} repeatedly exits with code {{ $labels.exit_code }}"
          expr: |
            sum by (namespace, pod, container, exit_code) (
              increase(terminated_containers_total{exit_code!="0"}[15m])
            ) > 5
          for: 10m
          labels:
            severity: critical
