---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat
data:
  # server
  HOST: "0.0.0.0"
  PORT: "3080"
  MONGO_URI: "mongodb://librechat-mongodb.servitor-apps.svc.cluster.local:27017/LibreChat"
  DOMAIN_CLIENT: "http://librechat-app.servitor-apps.svc.cluster.local:3080"
  DOMAIN_SERVER: "http://librechat-app.servitor-apps.svc.cluster.local:3080"
  NO_INDEX: "true"
  TRUST_PROXY: "1"
  NODE_MAX_OLD_SPACE_SIZE: "6144"
  # auth
  # logging
  CONSOLE_JSON: "false"
  DEBUG_LOGGING: "true"
  DEBUG_CONSOLE: "false"
  AGENT_DEBUG_LOGGING: "false"
  # Search
  SEARCH: "true"
  MEILI_HOST: "http://meilisearch.selfhosted-apps.svc.cluster.local:7700"
  # RAG
  RAG_API_URL: "http://librechat-api.servitor-apps.svc.cluster.local:8000"
